CREATE OR REPLACE STORAGE INTEGRATION I_META
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '1e3588c1-4b62-42c7-8d3a-640f42dadef5'
  STORAGE_ALLOWED_LOCATIONS = ('azure://storedir.blob.core.windows.net/prod')
  ;